THISDIR="css"
CANDIDATES_DIR=../candidates

build:
	# Append our CSS files to tempest.css in candidates
	cat style.css >> ${CANDIDATES_DIR}/tempest.css
	@echo "*** $(THISDIR): completed build ***"

package:
	@echo "*** $(THISDIR): completed package ***"

release:
	@echo "*** $(THISDIR): completed release ***"

clean:
	@echo "*** $(THISDIR): completed clean ***"

test:
	@echo "*** $(THISDIR): completed test ***"
